project:
  type: website
  output-dir: quarto-site
website:
  title: "saurabhkrsingh.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: mypage
      - href: docs/Saurabh_CV.pdf
        text: CV
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



